apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-service
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: payroll-service
  template:
    metadata:
      labels:
        app: payroll-service
    spec:
      containers:
      - image: docker.io/nicholasnogradi1245/payroll-app:latest
        name: payroll-service
        ports:
        - containerPort: 8081