service:
    name: payroll_service
    identifier: payrollservice
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: payrollservice
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            paths:
                                - manifests/deployment.yml
                                - manifests/payroll-service.yml
                            repoName: PayrollService
                            branch: main
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false